version: 1.0.{build}
environment:
  # Windows specific setting
  nodejs_version: "12"
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: >-
      dotnet restore;nuget restore

install:
  # Windows specific setting
  - ps: if ($IsWindows -or $ENV:OS) { Install-Product node '12' x64 } 
  - ps: node --version
  - ps: node -p "process.arch"
  - ps: npm --version

build:
  project: PdfjsSharp.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

# Linux specific setting
stack: node 10

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

deploy:
- provider: NuGet
  api_key:
    secure: CTISdGCfnpyC7Rh5vs1pgbuISrkWF34sot0SyVgvu0HQxhNNd+V0Gc4MS+rtJttB
  on:
    branch: main
  skip_symbols: false
- provider: GitHub
  auth_token:
    secure: LCcdAY3jdn94v+LnQS1yyjB6pqe7AKMaTEV9MZCfqumHWRNDDi1kGpvLyytAdW9E
  on:
    branch: main
