# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
skip_tags: true
configuration: Release
before_build:
  - ps: >-
      nuget restore
build:
  project: PdfjsSharp.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PdfjsSharp.*.*nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
    on:
      branch: master
