name: .NET build and test
env:
  CURRENT_VERSION: 1.1.${{ github.run_number }}
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  deployRelease:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      run: |
          dotnet nuget push ./PdfjsSharp/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
    - uses: papeloto/action-zip@v1
      with:
          files: ./PdfjsSharp/bin/Release/net6.0/publish/
          dest: PdfjsSharp.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Release Build"
        files: |
          PdfjsSharp.zip

  deployTest:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: NugetPush
      run: |
          ls ./PdfjsSharp/bin/Release
          dotnet nuget push ./PdfjsSharp/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json
    - uses: papeloto/action-zip@v1
      with:
          files: ./PdfjsSharp/bin/Release/
          dest: PdfjsSharp.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-prerelease"
        prerelease: true
        title: "Prerelease Build"
        files: |
          PdfjsSharp.zip
